name: build

on:
  push:
    paths-ignore: ['**.md', '**.svg', '**.png']
  pull_request:
    paths-ignore: ['**.md', '**.svg', '**.png']

jobs:

  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        mkdir -p tools
        echo "Installing xtensa-lx106-elf"
        wget -qO- https://github.com/earlephilhower/esp-quick-toolchain/releases/download/3.2.0-gcc10.3/x86_64-linux-gnu.xtensa-lx106-elf-c791b74.230224.tar.gz | tar xz -C ./tools
        echo "Installing xtensa-esp32-elf"
        wget -qO- https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz | tar xz -C ./tools
        echo "Installing WABT"
        wget -qO- https://github.com/WebAssembly/wabt/releases/download/1.0.36/wabt-1.0.36-ubuntu-20.04.tar.gz | tar xz -C ./tools
        echo "Installing MicroPython"
        wget -qO- https://github.com/micropython/micropython/releases/download/v1.23.0/micropython-1.23.0.tar.xz | tar xJ -C ./tools

        pip3 install -U pyelftools

        sudo apt update
        sudo apt install build-essential gcc-arm-none-eabi

    - name: Run builds
      run: |
        export PATH=$PWD/tools/xtensa-lx106-elf/bin:$PATH
        export PATH=$PWD/tools/xtensa-esp32-elf/bin:$PATH
        export PATH=$PWD/tools/wabt-1.0.36/bin:$PATH

        export MPY_DIR=$PWD/tools/micropython-1.23.0

        for A in x86 x64 armv6m armv7m armv7emsp armv7emdp xtensa xtensawin; do
          echo "=================="
          make clean all ARCH=$A
        done

        GREEN="\033[0;32m"
        NC="\033[0m"

        echo "=================="
        echo -e "${GREEN} BUILD OK ${NC}"
        echo "=================="

